#!/usr/bin/python3

import os
import subprocess
import tkinter as tk
from tkinter import filedialog
import shutil

class XCATInstaller:
    def __init__(self, root):
        self.root = root
        self.root.title("xCAT Installer")
        self.root.minsize(700, 400)

        self.status_label = tk.Label(root, text="")
        self.status_label.pack()

        self.browse_iso_button = tk.Button(root, text="Browse ISO", command=self.browse_iso)
        self.browse_iso_button.pack()

        self.copy_cds_button = tk.Button(root, text="Copy CDS", command=self.copy_cds)
        self.copy_cds_button.pack()

        self.create_image_button = tk.Button(root, text="Create Image", command=self.create_image)
        self.create_image_button.pack()

    def check_root(self):
        return os.geteuid() == 0

    def browse_iso(self):
        iso_path = filedialog.askopenfilename(title="Select an ISO file")
        if os.path.exists(iso_path):
            self.status_label.config(text=f"Selected ISO file: {iso_path}")
        else:
            self.status_label.config(text="ISO file not found.")
        self.status_label.update()

    def copy_cds(self):
        iso_path = filedialog.askopenfilename(title="Select an ISO file")
        if iso_path:
            target_dir = "/path/to/destination/directory"  # Set your destination directory
            self.status_label.config(text=f"Copying ISO file to {target_dir}...")
            self.status_label.update()
            try:
                shutil.copy(iso_path, target_dir)
                self.status_label.config(text="ISO file copied successfully.")
            except Exception as e:
                self.status_label.config(text=f"Error copying ISO file: {e}")

    def create_image(self):
        os.system("dd if=/dev/sr0 of=/root/.iso && \
        copycds /root/.iso && \
        lsdef -t osimage  && \
        genimage centos7.9-x86_64-netboot-compute && \
        mkdir -p /install/custom/netboot && \
        chdef -t osimage centos7.9-x86_64-netboot-compute synclists=\"/install/custom/netboot/compute.synclist\" && \
        echo \"/etc/passwd -> /etc/passwd\" > /install/custom/netboot/compute.synclist && \
        echo \"/etc/shadow -> /etc/shadow\" >> /install/custom/netboot/compute.synclist && \
        echo \"/etc/group -> /etc/group\" >> /install/custom/netboot/compute.synclist && \
        echo \"/etc/hosts -> /etc/hosts\" >> /install/custom/netboot/compute.synclist && \
        packimage centos7.9-x86_64-netboot-compute")

    def run(self):
        self.root.mainloop()

if __name__ == "__main__":
    root = tk.Tk()
    installer = XCATInstaller(root)
    installer.run()

